import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/shared/Navbar";
import Footer from "./component/shared/Footer";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'
import { ColorSchemeScript, MantineProvider } from '@mantine/core';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ColorSchemeScript defaultColorScheme="auto" />
        <Navbar></Navbar>
        <ToastContainer />
        <MantineProvider defaultColorScheme="auto">
        {children}
        </MantineProvider>
        <Footer></Footer>
      </body>
    </html>
  );
}
